version: '3'
services:
  db:
    image: postgres:latest
    #restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  app:
    #image: registry.stageppp.ru/pppp/garbage:latest
    build: .
    #restart: always
    environment:
      db_host: db
    ports:
      - "5000:5000"
